version: "3"

services:
  rest_app:
    container_name: rest_app
    image: amtoft/devops_rest_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always